name: front-tests-epic-to-staging-pr

on: pull_request

jobs:
  front-tests-epic-to-staging-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto front and run tests
        run: npm i && npm run test
